feat(nextjs-api-dev-proxy): add disable config
infinum/react-nuts-and-bolts pull request #16
Opened 2023-02-15 13:57 UTC by kristian240

Closes #15

2023-02-15 14:16 UTC, isBatak approved these changes

2023-02-15 14:21 UTC, isBatak approved these changes

2023-02-15 14:21 UTC, isBatak commented on packages/nextjs-api-dev-proxy/src/nextjs-api-dev-proxy.ts
> +	 *   disable: (req) => req.headers['x-skip-proxy'] === 'true'
Nice addition with `req`, so poverful!

2023-02-15 14:22 UTC, isBatak requested changes

2023-02-15 14:22 UTC, isBatak commented on packages/nextjs-api-dev-proxy/src/nextjs-api-dev-proxy.ts
> +	 * Used for disabling the proxy. By default it's enabled only in development.
We should add this to readme

2023-02-16 05:33 UTC, kristian240 commented on packages/nextjs-api-dev-proxy/src/nextjs-api-dev-proxy.ts
> +	 *   disable: (req) => req.headers['x-skip-proxy'] === 'true'
Kudos to GH Copilot 😄

2023-02-16 07:08 UTC, isBatak approved these changes

2023-02-21 11:20 UTC, merged